### DISCUSSION TITLE
Including other plugins

### DISCUSSION THREAD

**Discussion by AureliusHogan** [CarbonPackages/Carbon.IncludeAssets#15] [General]
I've got a project where I'm using IncludeAssets. This works fine. Thanks!!!

So now I had to add DL.Gallery which has, as natural, their own CSS and JS files which I would like to add with IncludeAssets. But how can I do this without copying those files to my sitepackage?

```
Carbon:
  IncludeAssets:
    Packages:
      Default:
        Path:
          File:
            CSS: Public/_css
            JS: Public/_js
        General:
          Head:
            - styles.min.css
            - BoostrapLightbox.css
          Body:
            - jquery-3.5.1.min.js
            - BootstrapLightbox.min.js
            - main.js
```

So the BootstrapLightbox.css and BootstrapLightbox.min.js are in a different Path. 

How would I have to configure this?

**Comment by jonnitto** [comment]
Something like this:

```yaml
Carbon:
  IncludeAssets:
    Packages:
      'aa_YourSitePackage':
        Path:
          File:
            CSS: Public/_css
            JS: Public/_js
        General:
          Head:
            - styles.min.css
            - jquery-3.5.1.min.js[defer]
            - main.js[defer]
      'DL.Gallery':
        Package: 'DL.Gallery'
        Path:
          File:
            CSS: "Public/Styles"
            JS: "Public/JavaScript"
        General:
          Head:
            - BoostrapLightbox.css
            - BootstrapLightbox.min.js[defer]
```


As the order where the files are included is important, you have to define the order with the key under `Packages`. (e.g. `aa_YourSitePackage` or `DL.Gallery`).

The setting `Package: 'DL.Gallery'` says that the files are not in the site package, but in the gallery package from Daniel.

> **Note:** 
> I would set the Javascript into the head and add the attribute `defer` to the script tag. You can do this with square brackets: `YouFileName.js[defer]`
> You can read more about this in the first section in the readme
