### ISSUE TITLE
Browser specific includes

### ISSUE THREAD

**Issue by ErichManser** [CarbonPackages/Carbon.IncludeAssets#10]
This extensions works fine. Great job!!

But I'm missing browser specific includes like:
```HTML
<!--[if lt IE 9]>
  <script src="_js/html5shiv-3.7.2.min.js"></script>
  <script src="_js/respond-1.4.2.min.js"></script>
<![endif]-->
```

Or ist there a possibility thats currently not described?

**Comment by jonnitto** [comment]
No, currently this is not possible, but I'll add it to the roadmap.

**Comment by jonnitto** [comment]
As there could be multiple files in one commend I suggest a setting like this:

```yaml
Carbon:
  IncludeAssets:
    Packages:
      KEY:
         wrapper: '<!--[if lt IE 9]>%tags<![endif]-->'
```

What do you think, @ErichManser?
